#!/bin/bash

#SBATCH --job-name="Airfoils"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=128
#SBATCH --mem=250G
#SBATCH -t 167:00:00
#SBATCH --export=ALL
#SBATCH --account=ucb198
#SBATCH --qos=oneweek
cp -rf /expanse/lustre/scratch/h7ris/temp_project/AirOpt/ /scratch/$USER/job_$SLURM_JOB_ID/

cd /scratch/$USER/job_$SLURM_JOB_ID/AirOpt

timeout 166h matlab -batch "run('AirOptimizer.m');exit;" 2>&1 | tee log # Change this line

cd ..

# Move the log file
mv ./AirOpt ./AirOptOut
cp -r ./* /expanse/lustre/scratch/h7ris/temp_project/AirOpt/
